FROM docker.io/library/centos:8

RUN yum install epel-release -y \
    && yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto c-ares-devel libev-devel libsodium-devel mbedtls-devel git curl -y \
    && git clone https://github.com/shadowsocks/shadowsocks-libev.git && cd shadowsocks-libev && git submodule update --init --recursive \
    && ./autogen.sh && ./configure && make && mv ./src/ss-* /usr/bin && cd .. && rm -rf shadowsocks-libev \
    && yum autoremove gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto c-ares-devel libev-devel libsodium-devel mbedtls-devel git -y \
    && yum install libev c-ares libsodium mbedtls -y \
    && yum clean all

RUN curl -L https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz | tar -zx \
    && mv v2ray-plugin_linux_amd64 /usr/bin/v2ray-plugin

CMD ["/usr/bin/ss-local","-c","/etc/shadowsocks-libev/config.json"]
